package telerik

func GetTemplate() string {
  return `
{{define "KendoUiAlert : KendoUiDialog"}}$("#{{.HtmlId}}").kendoAlert({ {{if (.Messages) ne nil }}messages: {{.Messages | safeHTML }},{{end}} });{{end}}
{{define "KendoUiAutoComplete"}}$("#{{.HtmlId}}").kendoAutoComplete({ {{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.AutoWidth) ne 0 }}{{if (.AutoWidth) eq -1}}autoWidth: false{{else}}autoWidth: true{{end}},{{end}}{{if (.DataSource) ne nil }}dataSource: {{.DataSource | safeHTML }},{{end}}{{if (.ClearButton) ne 0 }}{{if (.ClearButton) eq -1}}clearButton: false{{else}}clearButton: true{{end}},{{end}}{{if (.DataTextField) ne "" }}dataTextField: {{.DataTextField}},{{end}}{{if (.Delay) ne 0 }}delay: {{.Delay}},{{end}}{{if (.Enable) ne 0 }}{{if (.Enable) eq -1}}enable: false{{else}}enable: true{{end}},{{end}}{{if (.EnforceMinLength) ne 0 }}{{if (.EnforceMinLength) eq -1}}enforceMinLength: false{{else}}enforceMinLength: true{{end}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}}{{if (.FixedGroupTemplate) ne "" }}fixedGroupTemplate: {{.FixedGroupTemplate}},{{end}}{{if (.FooterTemplate) ne "" }}footerTemplate: {{.FooterTemplate}},{{end}}{{if (.GroupTemplate) ne "" }}groupTemplate: {{.GroupTemplate}},{{end}}{{if (.Height) ne 0 }}height: {{.Height}},{{end}}{{if (.HighlightFirst) ne ""}}highlightFirst: {{.HighlightFirst}},{{end}}{{if (.IgnoreCase) ne ""}}ignoreCase: {{.IgnoreCase}},{{end}}{{if (.MinLength) ne 0 }}minLength: {{.MinLength}},{{end}}{{if (.NoDataTemplate) ne "" }}noDataTemplate: {{.NoDataTemplate}},{{end}}{{if (.Placeholder) ne "" }}placeholder: {{.Placeholder}},{{end}}{{if (.Popup) ne nil }}popup: {{.Popup | safeHTML }},{{end}}{{if (.Separator) ne "" }}separator: {{.Separator}},{{end}}{{if (.Suggest) ne ""}}suggest: {{.Suggest}},{{end}}{{if (.HeaderTemplate) ne "" }}headerTemplate: {{.HeaderTemplate}},{{end}}{{if (.Template) ne "" }}template: {{.Template}},{{end}}{{if (.Value) ne "" }}value: {{.Value}},{{end}}{{if (.ValuePrimitive) ne ""}}valuePrimitive: {{.ValuePrimitive}},{{end}}{{if .Virtual.IsSet}}virtual: {{template "KendoVirtual" .Virtual}},{{end}} });{{end}}
{{define "KendoAnimation"}}{ {{if .Close.IsSet}}Close: {{template "KendoClose" .Close}},{{end}}{{if .Open.IsSet}}Open: {{template "KendoOpen" .Open}},{{end}} }{{end}}
{{define "KendoClose"}}{ {{if (.Duration) ne 0 }}Duration: {{.Duration}},{{end}}{{if (.Effects) ne "" }}Effects: {{.Effects}},{{end}} }{{end}}
{{define "KendoOpen"}}{ {{if (.Duration) ne 0 }}Duration: {{.Duration}},{{end}}{{if (.Effects) ne "" }}Effects: {{.Effects}},{{end}} }{{end}}
{{define "KendoVirtual"}}{ {{if (.ItemHeight) ne 0 }}ItemHeight: {{.ItemHeight}},{{end}}{{if (.MapValueTo) ne "" }}MapValueTo: {{.MapValueTo}},{{end}}{{if (.ValueMapper) ne "" }}ValueMapper: {{.ValueMapper}},{{end}} }{{end}}
{{define "KendoUiButton"}}$("#{{.HtmlId}}").kendoButton({ {{if (.Enable) ne ""}}enable: {{.Enable}},{{end}}{{if (.Icon) ne "" }}icon: {{.Icon}},{{end}}{{if (.ImageUrl) ne "" }}imageUrl: {{.ImageUrl}},{{end}}{{if (.SpriteCssClass) ne "" }}spriteCssClass: {{.SpriteCssClass}},{{end}} });{{end}}
{{define "KendoUiCalendar"}}$("#{{.HtmlId}}").kendoCalendar({ {{if (.Culture) ne "" }}culture: {{.Culture}},{{end}}{{if (.Dates) ne nil }}dates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Depth) ne "" }}depth: {{.Depth}},{{end}}{{if (.DisableDates) ne nil }}disableDates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Footer) ne "" }}footer: {{.Footer}},{{end}}{{if (.Format) ne "" }}format: {{.Format}},{{end}}time.Time{{if .Messages.IsSet}}messages: {{template "KendoMessages" .Messages}},{{end}}time.Time{{if .Month.IsSet}}month: {{template "KendoMonth" .Month}},{{end}}{{if (.Selectable) ne "" }}selectable: {{.Selectable}},{{end}}{{if (.SelectDates) ne nil }}selectDates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.WeekNumber) ne ""}}weekNumber: {{.WeekNumber}},{{end}}{{if (.Start) ne "" }}start: {{.Start}},{{end}}time.Time });{{end}}
{{define "KendoMessages"}}{ {{if (.WeekColumnHeader) ne "" }}WeekColumnHeader: {{.WeekColumnHeader}},{{end}} }{{end}}
{{define "KendoMonth"}}{ {{if (.Content) ne "" }}Content: "{{.Content}}",{{end}}{{if (.WeekNumber) ne "" }}WeekNumber: {{.WeekNumber}},{{end}}{{if (.Empty) ne "" }}Empty: {{.Empty}},{{end}} }{{end}}
{{define "KendoUiColorPalette"}}$("#{{.HtmlId}}").kendoColorPalette({ {{if (.Palette) ne "" }}palette: {{.Palette}},{{end}}{{if (.Columns) ne 0 }}columns: {{.Columns}},{{end}}{{if .TileSize.IsSet}}tileSize: {{template "KendoTileSize" .TileSize}},{{end}}{{if (.Value) ne "" }}value: {{.Value}},{{end}} });{{end}}
{{define "KendoTileSize"}}{ {{if (.Width) ne 0 }}Width: {{.Width}},{{end}}{{if (.Height) ne 0 }}Height: {{.Height}},{{end}} }{{end}}
{{define "KendoUiColorPicker"}}$("#{{.HtmlId}}").kendoColorPicker({ {{if (.Buttons) ne ""}}buttons: {{.Buttons}},{{end}}{{if (.ClearButton) ne ""}}clearButton: {{.ClearButton}},{{end}}{{if (.Columns) ne 0 }}columns: {{.Columns}},{{end}}{{if .TileSize.IsSet}}tileSize: {{template "KendoTileSize" .TileSize}},{{end}}{{if .Messages.IsSet}}messages: {{template "KendoMessages" .Messages}},{{end}}{{if (.Palette) ne "" }}palette: {{.Palette}},{{end}}{{if (.Opacity) ne ""}}opacity: {{.Opacity}},{{end}}{{if (.Preview) ne ""}}preview: {{.Preview}},{{end}}{{if (.ToolIcon) ne "" }}toolIcon: {{.ToolIcon}},{{end}}{{if (.Value) ne "" }}value: {{.Value}},{{end}} });{{end}}
{{define "KendoUiComboBox"}}$("#{{.HtmlId}}").kendoComboBox({ {{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.AutoBind) ne ""}}autoBind: {{.AutoBind}},{{end}}{{if (.AutoWidth) ne ""}}autoWidth: {{.AutoWidth}},{{end}}{{if (.CascadeFrom) ne "" }}cascadeFrom: {{.CascadeFrom}},{{end}}{{if (.CascadeFromField) ne "" }}cascadeFromField: {{.CascadeFromField}},{{end}}{{if (.ClearButton) ne ""}}clearButton: {{.ClearButton}},{{end}}{{if (.DataSource) ne nil }}dataSource: {{.DataSource | safeHTML }},{{end}}{{if (.DataTextField) ne "" }}dataTextField: {{.DataTextField}},{{end}}{{if (.DataValueField) ne "" }}dataValueField: {{.DataValueField}},{{end}}{{if (.Delay) ne 0 }}delay: {{.Delay}},{{end}}{{if (.Enable) ne ""}}enable: {{.Enable}},{{end}}{{if (.EnforceMinLength) ne ""}}enforceMinLength: {{.EnforceMinLength}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}}{{if (.FixedGroupTemplate) ne "" }}fixedGroupTemplate: {{.FixedGroupTemplate}},{{end}}{{if (.FooterTemplate) ne "" }}footerTemplate: {{.FooterTemplate}},{{end}}{{if (.GroupTemplate) ne "" }}groupTemplate: {{.GroupTemplate}},{{end}}{{if (.Height) ne 0 }}height: {{.Height}},{{end}}{{if (.HighlightFirst) ne ""}}highlightFirst: {{.HighlightFirst}},{{end}}{{if (.IgnoreCase) ne ""}}ignoreCase: {{.IgnoreCase}},{{end}}{{if (.Index) ne 0 }}index: {{.Index}},{{end}}{{if (.MinLength) ne 0 }}minLength: {{.MinLength}},{{end}}{{if (.NoDataTemplate) ne "" }}noDataTemplate: {{.NoDataTemplate}},{{end}}{{if (.Placeholder) ne "" }}placeholder: {{.Placeholder}},{{end}}{{if .Popup.IsSet}}popup: {{template "KendoPopup" .Popup}},{{end}}{{if (.Suggest) ne ""}}suggest: {{.Suggest}},{{end}}{{if (.SyncValueAndText) ne ""}}syncValueAndText: {{.SyncValueAndText}},{{end}}{{if (.HeaderTemplate) ne "" }}headerTemplate: {{.HeaderTemplate}},{{end}}{{if (.Template) ne "" }}template: {{.Template}},{{end}}{{if (.Text) ne "" }}text: {{.Text}},{{end}}{{if (.Value) ne "" }}value: {{.Value}},{{end}}{{if (.ValuePrimitive) ne ""}}valuePrimitive: {{.ValuePrimitive}},{{end}}{{if .Virtual.IsSet}}virtual: {{template "KendoVirtual" .Virtual}},{{end}} });{{end}}
{{define "KendoPopup"}}{ {{if (.AppendTo) ne "" }}AppendTo: {{.AppendTo}},{{end}}{{if (.Origin) ne "" }}Origin: {{.Origin}},{{end}}{{if (.Position) ne "" }}Position: {{.Position}},{{end}} }{{end}}
{{define "KendoUiContextMenu"}}$("#{{.HtmlId}}").kendoContextMenu({ {{if (.AlignToAnchor) ne ""}}alignToAnchor: {{.AlignToAnchor}},{{end}}{{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.AppendTo) ne "" }}appendTo: {{.AppendTo}},{{end}}{{if (.CloseOnClick) ne ""}}closeOnClick: {{.CloseOnClick}},{{end}}{{if (.CopyAnchorStyles) ne ""}}copyAnchorStyles: {{.CopyAnchorStyles}},{{end}}{{if (.DataSource) ne nil }}dataSource: {{.DataSource | safeHTML }},{{end}}{{if (.Direction) ne "" }}direction: {{.Direction}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}}{{if (.HoverDelay) ne 0 }}hoverDelay: {{.HoverDelay}},{{end}}{{if (.Orientation) ne "" }}orientation: {{.Orientation}},{{end}}{{if (.PopupCollision) ne "" }}popupCollision: {{.PopupCollision}},{{end}}{{if (.ShowOn) ne "" }}showOn: {{.ShowOn}},{{end}}{{if (.Target) ne "" }}target: {{.Target}},{{end}} });{{end}}
{{define "KendoUiDateInput"}}$("#{{.HtmlId}}").kendoDateInput({ {{if (.Format) ne "" }}format: {{.Format}},{{end}}time.Timetime.Timetime.Time{{if .Messages.IsSet}}messages: {{template "KendoMessages" .Messages}},{{end}} });{{end}}
{{define "KendoUiDatePicker"}}$("#{{.HtmlId}}").kendoDatePicker({ {{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.ARIATemplate) ne "" }}ARIATemplate: {{.ARIATemplate}},{{end}}{{if (.Culture) ne "" }}culture: {{.Culture}},{{end}}{{if (.DateInput) ne ""}}dateInput: {{.DateInput}},{{end}}{{if (.Dates) ne nil }}dates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Depth) ne "" }}depth: {{.Depth}},{{end}}{{if (.DisableDates) ne nil }}disableDates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Footer) ne "" }}footer: {{.Footer}},{{end}}{{if (.Format) ne "" }}format: {{.Format}},{{end}}time.Timetime.Time{{if .Month.IsSet}}month: {{template "KendoMonth" .Month}},{{end}}{{if (.WeekNumber) ne ""}}weekNumber: {{.WeekNumber}},{{end}}{{if (.ParseFormats) ne nil }}parseFormats: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Start) ne "" }}start: {{.Start}},{{end}}time.Time });{{end}}
{{define "KendoUiDateTimePicker"}}$("#{{.HtmlId}}").kendoDateTimePicker({ {{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.ARIATemplate) ne "" }}ARIATemplate: {{.ARIATemplate}},{{end}}{{if (.Culture) ne "" }}culture: {{.Culture}},{{end}}{{if (.DateInput) ne ""}}dateInput: {{.DateInput}},{{end}}{{if (.Dates) ne nil }}dates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Depth) ne "" }}depth: {{.Depth}},{{end}}{{if (.DisableDates) ne nil }}disableDates: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Footer) ne "" }}footer: {{.Footer}},{{end}}{{if (.Format) ne "" }}format: {{.Format}},{{end}}{{if (.Interval) ne 0 }}interval: {{.Interval}},{{end}}time.Timetime.Time{{if .Month.IsSet}}month: {{template "KendoMonth" .Month}},{{end}}{{if (.WeekNumber) ne ""}}weekNumber: {{.WeekNumber}},{{end}}{{if (.ParseFormats) ne nil }}parseFormats: [{{range $k, $v := .}}{{$v | safeHTML }},{{end}}],{{end}}{{if (.Start) ne "" }}start: {{.Start}},{{end}}{{if (.TimeFormat) ne "" }}timeFormat: {{.TimeFormat}},{{end}}time.Time });{{end}}
{{define "KendoUiDialog"}}$("#{{.HtmlId}}").kendoDialog({ {{if .Actions}}actions: {{template "KendoActions" .Actions}},{{end}}{{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.ButtonLayout) ne "" }}buttonLayout: {{.ButtonLayout}},{{end}}{{if (.Closable) ne ""}}closable: {{.Closable}},{{end}}{{if (.Content) ne "" }}content: "{{.Content}}",{{end}}{{if (.Height) ne 0 }}height: {{.Height}},{{end}}{{if (.MaxHeight) ne 0 }}maxHeight: {{.MaxHeight}},{{end}}{{if (.MaxWidth) ne 0 }}maxWidth: {{.MaxWidth}},{{end}}{{if .Messages.IsSet}}messages: {{template "KendoMessages" .Messages}},{{end}}{{if (.MinHeight) ne 0 }}minHeight: {{.MinHeight}},{{end}}{{if (.MinWidth) ne 0 }}minWidth: {{.MinWidth}},{{end}}{{if (.Modal) ne "" }}modal: {{.Modal}},{{end}}{{if (.Title) ne "" }}title: "{{.Title}}",{{end}}{{if (.Visible) ne ""}}visible: {{.Visible}},{{end}}{{if (.Width) ne 0 }}width: {{.Width}},{{end}} });{{end}}
{{define "KendoActions"}}[{{range $k, $v := .}}{ {{if ($v.Text) ne "" }}text: "{{$v.Text}}",{{end}}{{if ($v.Action) ne "" }}action: {{$v.Action}},{{end}}{{if ($v.Primary) ne "" }}primary: {{$v.Primary}},{{end}} },{{end}}]{{end}}
{{define "KendoUiDraggable"}}$("#{{.HtmlId}}").kendoDraggable({ {{if (.Axis) ne "" }}axis: {{.Axis}},{{end}}{{if (.AutoScroll) ne ""}}autoScroll: {{.AutoScroll}},{{end}}{{if (.Container) ne "" }}container: {{.Container}},{{end}}{{if (.CursorOffset) ne nil }}cursorOffset: {{.CursorOffset | safeHTML }},{{end}}{{if (.Distance) ne 0 }}distance: {{.Distance}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}}{{if (.Group) ne "" }}group: {{.Group}},{{end}}{{if (.Hint) ne "" }}hint: {{.Hint}},{{end}}{{if (.HoldToDrag) ne ""}}holdToDrag: {{.HoldToDrag}},{{end}}{{if (.Ignore) ne "" }}ignore: {{.Ignore}},{{end}} });{{end}}
{{define "KendoUiDropDownList"}}$("#{{.HtmlId}}").kendoDropDownList({ {{if .Animation.IsSet}}animation: {{template "KendoAnimation" .Animation}},{{end}}{{if (.AutoBind) ne ""}}autoBind: {{.AutoBind}},{{end}}{{if (.AutoWidth) ne ""}}autoWidth: {{.AutoWidth}},{{end}}{{if (.CascadeFrom) ne "" }}cascadeFrom: {{.CascadeFrom}},{{end}}{{if (.CascadeFromField) ne "" }}cascadeFromField: {{.CascadeFromField}},{{end}}{{if (.DataSource) ne nil }}dataSource: {{.DataSource | safeHTML }},{{end}}{{if (.DataTextField) ne "" }}dataTextField: {{.DataTextField}},{{end}}{{if (.DataValueField) ne "" }}dataValueField: {{.DataValueField}},{{end}}{{if (.Delay) ne 0 }}delay: {{.Delay}},{{end}}{{if (.Enable) ne ""}}enable: {{.Enable}},{{end}}{{if (.EnforceMinLength) ne ""}}enforceMinLength: {{.EnforceMinLength}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}}{{if (.FixedGroupTemplate) ne "" }}fixedGroupTemplate: {{.FixedGroupTemplate}},{{end}}{{if (.FooterTemplate) ne "" }}footerTemplate: {{.FooterTemplate}},{{end}}{{if (.GroupTemplate) ne "" }}groupTemplate: {{.GroupTemplate}},{{end}}{{if (.Height) ne 0 }}height: {{.Height}},{{end}}{{if (.IgnoreCase) ne ""}}ignoreCase: {{.IgnoreCase}},{{end}}{{if (.Index) ne 0 }}index: {{.Index}},{{end}}{{if (.MinLength) ne 0 }}minLength: {{.MinLength}},{{end}}{{if (.NoDataTemplate) ne "" }}noDataTemplate: {{.NoDataTemplate}},{{end}}{{if .Popup.IsSet}}popup: {{template "KendoPopup" .Popup}},{{end}}{{if (.OptionLabel) ne "" }}optionLabel: {{.OptionLabel}},{{end}}{{if (.OptionLabelTemplate) ne "" }}optionLabelTemplate: {{.OptionLabelTemplate}},{{end}}{{if (.HeaderTemplate) ne "" }}headerTemplate: {{.HeaderTemplate}},{{end}}{{if (.Template) ne "" }}template: {{.Template}},{{end}}{{if (.ValueTemplate) ne "" }}valueTemplate: {{.ValueTemplate}},{{end}}{{if (.Text) ne "" }}text: {{.Text}},{{end}}{{if (.Value) ne "" }}value: {{.Value}},{{end}}{{if (.ValuePrimitive) ne ""}}valuePrimitive: {{.ValuePrimitive}},{{end}}{{if .Virtual.IsSet}}virtual: {{template "KendoVirtual" .Virtual}},{{end}} });{{end}}
{{define "KendoUiDropTarget"}}$("#{{.HtmlId}}").kendoDraggable({ {{if (.Group) ne "" }}group: {{.Group}},{{end}} });{{end}}
{{define "KendoUiDropTargetArea"}}$("#{{.HtmlId}}").kendoDraggable({ {{if (.Group) ne "" }}group: {{.Group}},{{end}}{{if (.Filter) ne "" }}filter: {{.Filter}},{{end}} });{{end}}
`
}
